import { Nunito } from "next/font/google"

import './globals.css'

import ClientOnly from "./components/ClientOnly";
import RegisterModal from "./components/modals/RegisterModal";
import LoginModal from "./components/modals/LoginModal";
import RentModal from "./components/modals/RentModal";
import SearchModal from "./components/modals/SearchModal";
import EditModal from "./components/modals/EditModal";

import ToasterProvider from "./providers/ToasterProvider";

export const metadata = {
  title: 'BOOKIN.social',
  description: 'Generated by Bookin.social',
}

const font = Nunito({
  subsets: ['latin'],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className} suppressHydrationWarning={true}>
        <ClientOnly>
          <ToasterProvider />
          <SearchModal />
          <EditModal />
          <RentModal />
          <LoginModal />
          <RegisterModal />
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}